import type { GameState } from './types';
import { STOPS } from './world';

export interface UIActions { start: () => void; pause: () => void; resume: () => void; mute: () => void; fullscreen: () => void; unstuck: () => void; chooseJob?: (index: number) => void; returnHome?: () => void; nextDay?: () => void; }
export interface UIInfo { muted: boolean; targetName: string; targetDistance: number; targetBearing?: number; speed: number; status: string; timeRemaining?: number; }

// Pumpkin-tip dismissal: the bubble is dismissible per tip, and reappears when
// genuinely new information arrives (new mode, tutorial stage, or tip text).
// Pure so it can be unit-tested without a DOM.
export interface TipDismissal { lastKey: string | null; dismissedKey: string | null; }
export const emptyTipDismissal = (): TipDismissal => ({ lastKey: null, dismissedKey: null });
export function tipStateKey(mode: string, tutorialStage: number, text: string): string { return `${mode}|${tutorialStage}|${text}`; }
export function nextTipVisibility(prev: TipDismissal, mode: string, tutorialStage: number, status: string, text: string, timeRemaining?: number): { hidden: boolean; next: TipDismissal } {
  // key uses the *display* text so new information re-triggers the tip; wants
  // preserves the pre-existing visibility gating exactly (info.status-driven,
  // not state.message-driven).
  const key = tipStateKey(mode, tutorialStage, text);
  const next = key === prev.lastKey ? prev : { lastKey: key, dismissedKey: null };
  const wants = mode.includes('tutorial') || status !== '' || (mode === 'flight' && (timeRemaining ?? Infinity) <= 120);
  return { hidden: !wants || next.dismissedKey === key, next };
}
export function dismissTip(prev: TipDismissal): TipDismissal { return { ...prev, dismissedKey: prev.lastKey }; }

export const icon = (name: 'star'|'envelope'|'pause'|'sound'|'sound-off'|'fullscreen'|'home') => { const paths = { star:'<path d="m12 2 2.8 6.5L22 9l-5.4 4.7 1.6 7.1-6.2-3.7-6.2 3.7 1.6-7.1L2 9l7.2-.5Z"/>', envelope:'<rect x="3" y="5" width="18" height="14" rx="2"/><path d="m4 7 8 6 8-6"/>', pause:'<path d="M7 4h3v16H7zm7 0h3v16h-3z"/>', sound:'<path d="M4 10h4l5-4v12l-5-4H4zM16 9c1 .8 1 5.2 0 6m2-9c3 2.6 3 9.4 0 12"/>', 'sound-off':'<path d="M4 10h4l5-4v12l-5-4H4z"/><path d="M16 9l6 6M22 9l-6 6"/>', fullscreen:'<path d="M4 9V5h4m8 0h4v4M20 15v4h-4M8 19H4v-4"/>', home:'<path d="m3 11 9-8 9 8v9h-6v-6H9v6H3z"/>' }; return `<svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">${paths[name]}</svg>`; };
const money = (n: number) => `${Math.max(0, Math.round(n))} coins`;

export class UI {
  private el: Record<string, HTMLElement> = {}; private previousRevision = -1; private offersKey = ''; private tip = emptyTipDismissal();
  constructor(root: HTMLElement, actions: UIActions) {
    root.classList.add('meg-ui'); root.innerHTML = `
<header class="gamebar"><div class="gamebar-brand">MEG’S <span>Delivery Service</span></div><div class="gamebar-actions"><button class="icon-button" id="pause-btn" aria-label="Pause flight">${icon('pause')}</button></div></header><main class="screen-layer">
<section class="title-card panel" id="title-card"><div class="eyebrow">${icon('star')} A LITTLE WITCH. A BIG SKY.</div><h1>MEG’S<br><em>Delivery</em> Service</h1><p class="premise">Take on a parcel, then return home <b>before nightfall</b> to bank your earnings.</p><p class="key-hint desktop-hint">Steer with <kbd>WASD</kbd> / arrows · rise with <kbd>W</kbd> · hover with <kbd>Space</kbd></p><p class="key-hint touch-hint">Touch anywhere to fly · release the stick to slow down</p><button id="start-btn" class="primary-button">Learn to fly <span>→</span></button><div class="title-controls"><button id="fullscreen-btn">${icon('fullscreen')} Fullscreen</button><button id="mute-btn-title" class="icon-button icon-button-sm" aria-label="Mute audio">${icon('sound')}</button></div><footer>MADE OF LITTLE ADVENTURES <span class="desktop-hint">⌨</span><span class="touch-hint">touch to fly</span> <span class="build-sha">build ${__BUILD_SHA__}</span></footer></section>
<section class="offers-card panel menu-card" id="offers-card"><div class="eyebrow">${icon('envelope')} TODAY’S POST</div><h2>Choose a delivery</h2><p>Nightfall is already on its way. Pick one parcel and make it home with your earnings.</p><div class="offer-balances"><span>Satchel <b id="offer-earnings">0 coins</b></span><span>Banked <b id="offer-banked">0 coins</b></span></div><div id="offer-list" class="offer-list"></div><button id="return-home-btn" class="secondary-button">Return home</button></section>
<section class="summary-card panel menu-card" id="summary-card"><div class="eyebrow">${icon('star')} DAY’S END</div><h2 id="summary-heading">A lovely landing.</h2><p id="summary-copy"></p><div class="summary-stats"><div><span>Deliveries</span><b id="summary-deliveries">0</b></div><div><span>Earnings saved</span><b id="summary-earnings">0 coins</b></div></div><button id="next-day-btn" class="primary-button">Another day <span>→</span></button></section>
<section class="flight-hud" id="flight-hud"><div class="destination-card panel"><div class="eyebrow">${icon('envelope')} <span id="target-label">Next delivery</span></div><strong id="target-name">The village</strong><div class="target-direction"><span class="compass-arrow" id="target-arrow"></span><span id="target-distance">— m away</span><svg class="hourglass" id="hourglass" viewBox="0 0 40 48" aria-hidden="true"><defs><clipPath id="top-bulb"><polygon points="9,6 31,6 20,24"/></clipPath><clipPath id="bottom-bulb"><polygon points="9,42 31,42 20,24"/></clipPath></defs><path d="M9 6 H31 L20 24 L31 42 H9 L20 24 Z" fill="#fffdf5" fill-opacity="0.35" stroke="#55402e" stroke-width="2.5" stroke-linejoin="round"/><rect id="sand-top" x="9" y="6" width="22" height="18" fill="#e8b64c" clip-path="url(#top-bulb)"/><rect id="sand-bottom" x="9" y="42" width="22" height="0" fill="#e8b64c" clip-path="url(#bottom-bulb)"/><line class="sand-stream" x1="20" y1="24" x2="20" y2="30" stroke="#e8b64c" stroke-width="1.6" stroke-linecap="round"/><circle class="grain" cx="20" cy="22" r="1.3" fill="#e8b64c"/><circle class="grain grain-2" cx="20" cy="22" r="1" fill="#e8b64c"/><circle class="grain grain-3" cx="20" cy="22" r="1.1" fill="#e8b64c"/><line x1="6" y1="6" x2="34" y2="6" stroke="#55402e" stroke-width="3.5" stroke-linecap="round"/><line x1="6" y1="42" x2="34" y2="42" stroke="#55402e" stroke-width="3.5" stroke-linecap="round"/></svg></div></div><div class="tutorial-bubble" id="tutorial-bubble"><button class="bubble-close" id="bubble-close" aria-label="Dismiss tip">×</button><b>Pumpkin says:</b> <span id="tutorial-text"></span></div><div class="flight-readout panel"><span><b id="speed-value">0</b> m/s</span><span class="satchel-readout">Satchel <b id="flight-earnings">0</b></span></div></section>
<section class="pause-card panel menu-card" id="pause-card"><div class="eyebrow">${icon('star')} TAKING A BREATHER<button id="mute-btn-pause" class="icon-button icon-button-sm" aria-label="Mute audio" style="margin-left:auto">${icon('sound')}</button></div><h2>The sky will wait.</h2><p id="pause-reason"></p><p class="key-hint desktop-hint">When you return: <kbd>WASD</kbd> or arrows to steer · <kbd>Q</kbd>/<kbd>E</kbd> for speed</p><p class="key-hint touch-hint">When you return: touch anywhere to fly · release the stick to slow down</p><button id="resume-btn" class="primary-button">Continue flying <span>→</span></button><button id="unstuck-btn" class="secondary-button">Unstuck me</button></section></main>`;
    const get=(id:string)=>root.querySelector<HTMLElement>(`#${id}`)!; ['title-card','offers-card','summary-card','flight-hud','pause-card','hourglass','sand-top','sand-bottom','pause-reason','target-name','target-distance','target-arrow','target-label','tutorial-bubble','tutorial-text','bubble-close','speed-value','flight-earnings','mute-btn-title','mute-btn-pause','pause-btn','resume-btn','unstuck-btn','offer-list','return-home-btn','offer-earnings','offer-banked','summary-heading','summary-copy','summary-deliveries','summary-earnings','next-day-btn','start-btn'].forEach(id=>this.el[id]=get(id));
    const click=(id:string, action:()=>void)=>get(id).onclick=e=>{action();(e.currentTarget as HTMLElement).blur();}; click('start-btn',actions.start); click('pause-btn',actions.pause); click('resume-btn',actions.resume); click('unstuck-btn',actions.unstuck); click('mute-btn-title',actions.mute); click('mute-btn-pause',actions.mute);
    get('bubble-close').onclick=e=>{this.tip=dismissTip(this.tip);this.el['tutorial-bubble'].hidden=true;(e.currentTarget as HTMLElement).blur();}; click('return-home-btn',()=>actions.returnHome?.()); click('next-day-btn',()=>actions.nextDay?.()); get('fullscreen-btn').onclick=actions.fullscreen; get('offer-list').onclick=e=>{const b=(e.target as HTMLElement).closest<HTMLButtonElement>('[data-job]');if(b){actions.chooseJob?.(+b.dataset.job!);b.blur();}};
  }
  render(state: GameState, info: UIInfo): void {
    const menu=['offers','summary'].includes(state.mode), title=state.mode==='title', paused=!title&&state.paused; this.el['title-card'].hidden=!title; this.el['offers-card'].hidden=state.mode!=='offers'||paused; this.el['summary-card'].hidden=state.mode!=='summary'||paused; this.el['flight-hud'].hidden=title||menu||paused; this.el['pause-card'].hidden=!paused;
    // Hourglass: upper sand drains proportionate to time remaining; lower fills.
    // Shakes when 1 minute remains.
    if(info.timeRemaining!==undefined){ const f=Math.max(0,Math.min(1,info.timeRemaining/360));
      this.el['sand-top'].setAttribute('height',(18*f).toFixed(1));
      const bh=18*(1-f); this.el['sand-bottom'].setAttribute('height',bh.toFixed(1)); this.el['sand-bottom'].setAttribute('y',(42-bh).toFixed(1)); }
    this.el['hourglass'].classList.toggle('pulse',info.timeRemaining!==undefined&&info.timeRemaining<=60);
    this.el['hourglass'].classList.toggle('empty',info.timeRemaining!==undefined&&info.timeRemaining<=0);
    this.el['start-btn'].innerHTML=`${state.profile.tutorialDone?'Start a delivery day':'Learn to fly'} <span>→</span>`;
    this.el['target-name'].textContent=info.targetName; this.el['target-distance'].textContent=info.targetDistance>0?`${Math.round(info.targetDistance)} m away`:'Right here'; this.el['target-label'].textContent=state.run?.returning?'Return home':'Next delivery'; this.el['target-arrow'].style.transform=`rotate(${info.targetBearing??0}deg)`;
    this.el['speed-value'].textContent=String(Math.round(info.speed));
    for (const id of ['mute-btn-title', 'mute-btn-pause'] as const) {
      const btn = this.el[id];
      btn.classList.toggle('is-muted', info.muted);
      btn.setAttribute('aria-label', info.muted ? 'Unmute audio' : 'Mute audio');
      btn.innerHTML = icon(info.muted ? 'sound-off' : 'sound');
    } this.el['tutorial-text'].textContent=info.status||state.message||'Let’s take the scenic route!'; // INVARIANT: the dismissal key and the displayed tip text share one source expression (tipText).
    const tipText=info.status||state.message||''; const tip=nextTipVisibility(this.tip,state.mode,state.tutorialStage,info.status,tipText,info.timeRemaining); this.tip=tip.next; this.el['tutorial-bubble'].hidden=tip.hidden;
    this.el['flight-earnings'].textContent=money(state.run?.earnings??0); this.el['offer-earnings'].textContent=money(state.run?.earnings??0); this.el['offer-banked'].textContent=money(state.profile.coins); this.renderOffers(state);
    const s=state.summary, success=s?.success??false; this.el['summary-heading'].textContent=success?'A lovely landing.':'Rescued from nightfall.'; this.el['summary-copy'].textContent=success?`You banked ${money(s?.earnings??0)} after ${s?.deliveries??0} deliveries.`:'The unbanked satchel was lost, but tomorrow brings another chance.'; this.el['summary-deliveries'].textContent=String(s?.deliveries??0); this.el['summary-earnings'].textContent=money(s?.earnings??0); this.el['next-day-btn'].innerHTML=`${success?'Another day':'Back home'} <span>→</span>`;
    if(this.previousRevision!==state.revision){this.el['pause-reason'].textContent=state.pauseReason||'Rest your wings whenever you need.';this.previousRevision=state.revision;}
  }
  private renderOffers(state:GameState){if(state.mode!=='offers')return;this.el['return-home-btn'].hidden=(state.run?.deliveries??0)===0;const jobs=(state.run?.offers??[]).slice(0,2),key=jobs.map(j=>`${j.to}:${j.parcel}:${j.payout}`).join('|');if(key===this.offersKey)return;this.offersKey=key;this.el['offer-list'].innerHTML=jobs.map((job,index)=>{const stop=STOPS.find(s=>s.id===job.to),d=stop?Math.hypot(stop.position.x-state.player.position.x,stop.position.z-state.player.position.z):0;return `<button class="offer-button" data-job="${index}"><span><b>${stop?.name??job.to}</b><small>${d<115?'Short':'Long'} route · ${job.parcel} · ${Math.round(d)} m</small></span><strong>${money(job.payout)} <i>→</i></strong></button>`}).join('')}
}
