import type { GameState } from './types';
import { STOPS } from './world';

export interface UIActions { start: () => void; interact: () => void; hover: () => void; pause: () => void; resume: () => void; mute: () => void; quality: () => void; motion: () => void; fullscreen: () => void; chooseJob?: (index: number) => void; returnHome?: () => void; nextDay?: () => void; }
export interface UIInfo { muted: boolean; lowQuality: boolean; reducedMotion: boolean; targetName: string; targetDistance: number; canInteract: boolean; speed: number; status: string; timeRemaining?: number; homeBearing?: number; homeDistance?: number; homeMinimum?: number; targetAltitude?: number; interactionLabel?: string; }

// Pumpkin-tip dismissal: the bubble is dismissible per tip, and reappears when
// genuinely new information arrives (new mode, tutorial stage, or tip text).
// Pure so it can be unit-tested without a DOM.
export interface TipDismissal { lastKey: string | null; dismissedKey: string | null; }
export const emptyTipDismissal = (): TipDismissal => ({ lastKey: null, dismissedKey: null });
export function tipStateKey(mode: string, tutorialStage: number, text: string): string { return `${mode}|${tutorialStage}|${text}`; }
export function nextTipVisibility(prev: TipDismissal, mode: string, tutorialStage: number, status: string, text: string, timeRemaining?: number): { hidden: boolean; next: TipDismissal } {
  // key uses the *display* text so new information re-triggers the tip; wants
  // preserves the pre-existing visibility gating exactly (info.status-driven,
  // not state.message-driven).
  const key = tipStateKey(mode, tutorialStage, text);
  const next = key === prev.lastKey ? prev : { lastKey: key, dismissedKey: null };
  const wants = mode.includes('tutorial') || status !== '' || (mode === 'flight' && (timeRemaining ?? Infinity) <= 120);
  return { hidden: !wants || next.dismissedKey === key, next };
}
export function dismissTip(prev: TipDismissal): TipDismissal { return { ...prev, dismissedKey: prev.lastKey }; }

const icon = (name: 'star'|'envelope'|'pause'|'sound'|'fullscreen'|'home') => { const paths = { star:'<path d="m12 2 2.8 6.5L22 9l-5.4 4.7 1.6 7.1-6.2-3.7-6.2 3.7 1.6-7.1L2 9l7.2-.5Z"/>', envelope:'<rect x="3" y="5" width="18" height="14" rx="2"/><path d="m4 7 8 6 8-6"/>', pause:'<path d="M7 4h3v16H7zm7 0h3v16h-3z"/>', sound:'<path d="M4 10h4l5-4v12l-5-4H4zM16 9c1 .8 1 5.2 0 6m2-9c3 2.6 3 9.4 0 12"/>', fullscreen:'<path d="M4 9V5h4m8 0h4v4M20 15v4h-4M8 19H4v-4"/>', home:'<path d="m3 11 9-8 9 8v9h-6v-6H9v6H3z"/>' }; return `<svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">${paths[name]}</svg>`; };
const money = (n: number) => `${Math.max(0, Math.round(n))} coins`;
const clock = (n?: number) => n === undefined || !Number.isFinite(n) ? '--:--' : `${Math.floor(Math.max(0, Math.ceil(n))/60).toString().padStart(2,'0')}:${(Math.max(0, Math.ceil(n))%60).toString().padStart(2,'0')}`;

export class UI {
  private el: Record<string, HTMLElement> = {}; private previousRevision = -1; private offersKey = ''; private tip = emptyTipDismissal();
  constructor(root: HTMLElement, actions: UIActions) {
    root.classList.add('meg-ui'); root.innerHTML = `
<header class="gamebar"><div class="gamebar-brand">MEG’S <span>Delivery Service</span></div><div class="sun-pill"><i></i>Nightfall in <b id="countdown">--:--</b></div><div class="gamebar-actions"><button class="icon-button" id="audio-btn" aria-label="Mute audio">${icon('sound')}</button><button class="icon-button" id="pause-btn" aria-label="Pause flight">${icon('pause')}</button></div></header><main class="screen-layer">
<section class="title-card panel" id="title-card"><div class="eyebrow">${icon('star')} A LITTLE WITCH. A BIG SKY.</div><h1>MEG’S<br><em>Delivery</em> Service</h1><p class="premise">Take on a parcel, then return home <b>before nightfall</b> to bank your earnings.</p><p class="key-hint desktop-hint">Steer with <kbd>WASD</kbd> / arrows · rise with <kbd>W</kbd> · hover with <kbd>Space</kbd></p><p class="key-hint touch-hint">Drag the joystick to steer · slide for speed · tap Hover to hold still</p><button id="start-btn" class="primary-button">Learn to fly <span>→</span></button><div class="title-controls"><button id="quality-btn">Quality: <b>High</b></button><button id="motion-btn">Motion: <b>Full</b></button><button id="fullscreen-btn">${icon('fullscreen')} Fullscreen</button></div><footer>MADE OF LITTLE ADVENTURES <span class="desktop-hint">⌨</span><span class="touch-hint">touch to fly</span> <span class="build-sha">build ${__BUILD_SHA__}</span></footer></section>
<section class="offers-card panel menu-card" id="offers-card"><div class="eyebrow">${icon('envelope')} TODAY’S POST</div><h2>Choose a delivery</h2><p>Nightfall is already on its way. Pick one parcel and make it home with your earnings.</p><div class="offer-balances"><span>Satchel <b id="offer-earnings">0 coins</b></span><span>Banked <b id="offer-banked">0 coins</b></span></div><div id="offer-list" class="offer-list"></div><button id="return-home-btn" class="secondary-button">Return home</button></section>
<section class="summary-card panel menu-card" id="summary-card"><div class="eyebrow">${icon('star')} DAY’S END</div><h2 id="summary-heading">A lovely landing.</h2><p id="summary-copy"></p><div class="summary-stats"><div><span>Deliveries</span><b id="summary-deliveries">0</b></div><div><span>Earnings saved</span><b id="summary-earnings">0 coins</b></div></div><button id="next-day-btn" class="primary-button">Another day <span>→</span></button></section>
<section class="flight-hud" id="flight-hud"><div class="destination-card panel"><div class="eyebrow">${icon('envelope')} <span id="target-label">Next delivery</span></div><strong id="target-name">The village</strong><span id="target-distance">— m away</span><span class="altitude-note" id="altitude-note"></span><button id="interact-btn" class="context-button">Deliver parcel <kbd>Enter</kbd></button></div><div class="home-compass panel" id="home-compass"><span class="compass-arrow" id="compass-arrow">▲</span><div><b>Home</b><small id="home-distance">— m · — min</small></div></div><div class="tutorial-bubble" id="tutorial-bubble"><button class="bubble-close" id="bubble-close" aria-label="Dismiss tip">×</button><b>Pumpkin says:</b> <span id="tutorial-text"></span></div><div class="flight-readout panel"><span><b id="speed-value">0</b> m/s</span><span class="satchel-readout">Satchel <b id="flight-earnings">0</b></span><button id="hover-btn">Hover <kbd>Space</kbd></button></div></section>
<section class="pause-card panel menu-card" id="pause-card"><div class="eyebrow">${icon('star')} TAKING A BREATHER</div><h2>The sky will wait.</h2><p id="pause-reason"></p><p class="key-hint desktop-hint">When you return: <kbd>WASD</kbd> or arrows to steer · <kbd>Q</kbd>/<kbd>E</kbd> for speed</p><p class="key-hint touch-hint">When you return: drag the joystick to steer · slide for speed</p><button id="resume-btn" class="primary-button">Continue flying <span>→</span></button><div class="title-controls"><button id="pause-quality-btn">Quality</button><button id="pause-motion-btn">Motion</button></div></section></main>`;
    const get=(id:string)=>root.querySelector<HTMLElement>(`#${id}`)!; ['title-card','offers-card','summary-card','flight-hud','pause-card','countdown','pause-reason','target-name','target-distance','target-label','altitude-note','interact-btn','home-compass','compass-arrow','home-distance','tutorial-bubble','tutorial-text','bubble-close','speed-value','flight-earnings','hover-btn','audio-btn','pause-btn','resume-btn','quality-btn','motion-btn','pause-quality-btn','pause-motion-btn','offer-list','offer-earnings','offer-banked','summary-heading','summary-copy','summary-deliveries','summary-earnings','next-day-btn','start-btn'].forEach(id=>this.el[id]=get(id));
    const click=(id:string, action:()=>void)=>get(id).onclick=e=>{action();(e.currentTarget as HTMLElement).blur();}; click('start-btn',actions.start); click('interact-btn',actions.interact); click('hover-btn',actions.hover); click('pause-btn',actions.pause); click('resume-btn',actions.resume); click('audio-btn',actions.mute);
    get('bubble-close').onclick=e=>{this.tip=dismissTip(this.tip);this.el['tutorial-bubble'].hidden=true;(e.currentTarget as HTMLElement).blur();}; click('return-home-btn',()=>actions.returnHome?.()); click('next-day-btn',()=>actions.nextDay?.()); [get('quality-btn'),get('pause-quality-btn')].forEach(x=>x.onclick=actions.quality); [get('motion-btn'),get('pause-motion-btn')].forEach(x=>x.onclick=actions.motion); get('fullscreen-btn').onclick=actions.fullscreen; get('offer-list').onclick=e=>{const b=(e.target as HTMLElement).closest<HTMLButtonElement>('[data-job]');if(b){actions.chooseJob?.(+b.dataset.job!);b.blur();}};
  }
  render(state: GameState, info: UIInfo): void {
    const menu=['offers','summary'].includes(state.mode), title=state.mode==='title', paused=!title&&state.paused; this.el['title-card'].hidden=!title; this.el['offers-card'].hidden=state.mode!=='offers'||paused; this.el['summary-card'].hidden=state.mode!=='summary'||paused; this.el['flight-hud'].hidden=title||menu||paused; this.el['pause-card'].hidden=!paused;
    this.el['countdown'].textContent=clock(info.timeRemaining); this.el['countdown'].className=info.timeRemaining!==undefined&&info.timeRemaining<=30?'urgent':info.timeRemaining!==undefined&&info.timeRemaining<=60?'warning':''; this.el['start-btn'].innerHTML=`${state.profile.tutorialDone?'Start a delivery day':'Learn to fly'} <span>→</span>`;
    this.el['target-name'].textContent=info.targetName; this.el['target-distance'].textContent=info.targetDistance>0?`${Math.round(info.targetDistance)} m away`:'Right here'; this.el['target-label'].textContent=state.run?.returning?'Return home':'Next delivery'; const delta=info.targetAltitude??0; this.el['altitude-note'].textContent=info.targetAltitude===undefined?'':Math.abs(delta)<=2?'Level with pad':`${delta>=0?'Climb':'Descend'} ${Math.round(Math.abs(delta))} m`; this.el['altitude-note'].hidden=info.targetAltitude===undefined;
    const interact=this.el['interact-btn'] as HTMLButtonElement; const autoDelivering=state.haloFade>0||!!state.drop; interact.hidden=autoDelivering; interact.disabled=!info.canInteract; const actionLabel=info.interactionLabel||(state.run?.returning?'Bank earnings':'Deliver parcel'); interact.innerHTML=`${info.canInteract?actionLabel:state.drop?actionLabel:'Get a little closer'} <kbd>Enter</kbd>`; this.el['speed-value'].textContent=String(Math.round(info.speed)); const hover=this.el['hover-btn'] as HTMLButtonElement; hover.classList.toggle('is-active',state.player.hover); hover.innerHTML=`${state.player.hover?'Resume flight':'Hover'} <kbd>Space</kbd>`;
    this.el['audio-btn'].classList.toggle('is-muted',info.muted); this.el['audio-btn'].setAttribute('aria-label',info.muted?'Unmute audio':'Mute audio'); this.el['quality-btn'].innerHTML=`Quality: <b>${info.lowQuality?'Low':'High'}</b>`; this.el['motion-btn'].innerHTML=`Motion: <b>${info.reducedMotion?'Low':'Full'}</b>`; this.el['tutorial-text'].textContent=info.status||state.message||'Let’s take the scenic route!'; // INVARIANT: the dismissal key and the displayed tip text share one source expression (tipText).
    const tipText=info.status||state.message||''; const tip=nextTipVisibility(this.tip,state.mode,state.tutorialStage,info.status,tipText,info.timeRemaining); this.tip=tip.next; this.el['tutorial-bubble'].hidden=tip.hidden;
    this.el['home-compass'].hidden=info.homeBearing===undefined||state.mode!=='flight'; this.el['compass-arrow'].style.transform=`rotate(${info.homeBearing??0}deg)`; this.el['home-distance'].textContent=`${Math.round(info.homeDistance??0)} m · ${Math.max(1,Math.ceil((info.homeMinimum??0)/60))} min minimum · +30s margin`; this.el['flight-earnings'].textContent=money(state.run?.earnings??0); this.el['offer-earnings'].textContent=money(state.run?.earnings??0); this.el['offer-banked'].textContent=money(state.profile.coins); this.renderOffers(state);
    const s=state.summary, success=s?.success??false; this.el['summary-heading'].textContent=success?'A lovely landing.':'Rescued from nightfall.'; this.el['summary-copy'].textContent=success?`You banked ${money(s?.earnings??0)} after ${s?.deliveries??0} deliveries.`:'The unbanked satchel was lost, but tomorrow brings another chance.'; this.el['summary-deliveries'].textContent=String(s?.deliveries??0); this.el['summary-earnings'].textContent=money(s?.earnings??0); this.el['next-day-btn'].innerHTML=`${success?'Another day':'Back home'} <span>→</span>`;
    if(this.previousRevision!==state.revision){this.el['pause-reason'].textContent=state.pauseReason||'Rest your wings whenever you need.';this.previousRevision=state.revision;}
  }
  private renderOffers(state:GameState){if(state.mode!=='offers')return;const jobs=(state.run?.offers??[]).slice(0,2),key=jobs.map(j=>`${j.to}:${j.parcel}:${j.payout}`).join('|');if(key===this.offersKey)return;this.offersKey=key;this.el['offer-list'].innerHTML=jobs.map((job,index)=>{const stop=STOPS.find(s=>s.id===job.to),d=stop?Math.hypot(stop.position.x-state.player.position.x,stop.position.z-state.player.position.z):0;return `<button class="offer-button" data-job="${index}"><span><b>${stop?.name??job.to}</b><small>${d<115?'Short':'Long'} route · ${job.parcel} · ${Math.round(d)} m</small></span><strong>${money(job.payout)} <i>→</i></strong></button>`}).join('')}
}
